# Generated by Django 5.0.2 on 2024-02-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
